language: csharp
solution: NetServer.sln
mono:
  - latest

install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore StingyJunk.sln -Verbosity Detailed -NonInteractive -ConfigFile nuget.config
