language: csharp
solution: NetServer.sln
mono:
  - latest

before_install:
  - curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ls
  - mono nuget.exe restore .
  
notifications:
  email: false
