language: csharp
solution: NetServer.sln
mono:
  - latest

install:
  - cat Packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.0/build/net45/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props
  
notifications:
  email: false
